export const programingLang = [
  { display: "Javascript", value: "javascript" },
  { display: "Python", value: "python" },
  { display: "HTML/CSS", value: "htmlcss" },
  { display: "SQL", value: "sql" },
  { display: "Typescript", value: "typescript" },
  { display: "Bash/Shell", value: "bashshell" },
  { display: "Java", value: "java" },
  { display: "C#", value: "csharp" },
  { display: "C", value: "c" },
  { display: "C++", value: "cpp" },
  { display: "PHP", value: "php" },
  { display: "GO", value: "go" },
  { display: "Rust", value: "rust" },
  { display: "Kotlin", value: "kotlin" },
  { display: "Ruby", value: "ruby" },
  { display: "Lua", value: "lua" },
  { display: "Dart", value: "dart" },
  { display: ".Net", value: "dotnet" },
];

export const role = [
  { display: "Data science", value: "data_science" },
  {
    display: "Information Security Analysts",
    value: "information_security_analysts",
  },
  { display: "Software engineer", value: "software_engineer" },
  { display: "Web Developer", value: "web_developer" },
  { display: "Computer Systems Analyst", value: "computer_systems_analyst" },
  { display: "Database Administrator", value: "database_administrator" },
  { display: "Designer", value: "designer" },
  {
    display: "Computer Support Specialists",
    value: "computer_support_specialists",
  },
  { display: "Developer", value: "developer" },
  {
    display: "Information technology management",
    value: "information_technology_management",
  },
  { display: "Cloud Engineer", value: "cloud_engineer" },
  {
    display: "Computer Network Architects",
    value: "computer_network_architects",
  },
  { display: "Network Engineer", value: "network_engineer" },
  { display: "Project manager", value: "project_manager" },
  { display: "DevOps Engineer", value: "devops_engineer" },
  {
    display: "Mobile application developer",
    value: "mobile_application_developer",
  },
  { display: "Computer programmer", value: "computer_programmer" },
  { display: "Data Engineer", value: "data_engineer" },
  { display: "Front end Developer", value: "front_end_developer" },
  { display: "Product Manager", value: "product_manager" },
  { display: "Computer scientist", value: "computer_scientist" },
  { display: "Consultant", value: "consultant" },
  { display: "Content Marketing Manager", value: "content_marketing_manager" },
  { display: "Interaction design", value: "interaction_design" },
];

export const technology = [
  { display: "Angular", value: "angular" },
  { display: "ASP.NET/ASP.NET Core", value: "asp_net_core" },
  { display: "Express", value: "express" },
  { display: "Vue", value: "vue" },
  { display: "Spring", value: "spring" },
  { display: "Django", value: "django" },
  { display: "Flask", value: "flask" },
  { display: "Laravel", value: "laravel" },
  { display: "Ruby on Rails", value: "ruby_on_rails" },
  { display: "Symfony", value: "symfony" },
  { display: "Gatsby", value: "gatsby" },
  { display: "Sinatra", value: "sinatra" },
  { display: "CakePHP", value: "cakephp" },
  { display: "Horde", value: "horde" },
  { display: "Yii", value: "yii" },
  { display: "Zend", value: "zend" },
  { display: "Zikula", value: "zikula" },
  { display: "Bootstrap", value: "bootstrap" },
  { display: "Grails", value: "grails" },
  { display: "Play", value: "play" },
  { display: "Web2py", value: "web2py" },
  { display: "Lumen", value: "lumen" },
  { display: "TurboGears", value: "turbogears" },
  { display: "Phalcon", value: "phalcon" },
  { display: "FuelPHP", value: "fuelphp" },
  { display: "Spark", value: "spark" },
  { display: "Grok", value: "grok" },
  { display: "Mojolicious", value: "mojolicious" },
  { display: "Fat-Free Framework", value: "fat_free_framework" },
  { display: "Wicket", value: "wicket" },
  { display: "Yesod", value: "yesod" },
  { display: "Sencha Ext JS", value: "sencha_ext_js" },
  { display: "Nuxt.js", value: "nuxt_js" },
  { display: "Phoenix", value: "phoenix" },
  { display: "CodeIgniter", value: "codeigniter" },
  { display: "PHPixie", value: "phpixie" },
  { display: "Javalin", value: "javalin" },
  { display: "Silex", value: "silex" },
  { display: "Caliburn Micro", value: "caliburn_micro" },
  { display: "Ionic", value: "ionic" },
  { display: "Xamarin", value: "xamarin" },
  { display: "PhoneGap", value: "phonegap" },
  { display: "React Native", value: "react_native" },
  { display: "Corona", value: "corona" },
  { display: "jQuery Mobile", value: "jquery_mobile" },
  { display: "Flutter", value: "flutter" },
  { display: "Mobile Angular UI", value: "mobile_angular_ui" },
  { display: "Appcelerator Titanium", value: "appcelerator_titanium" },
  { display: "Swiftic", value: "swiftic" },
  { display: "NativeScript", value: "nativescript" },
  { display: "ReactJS", value: "react_js" },
  { display: "NextJS", value: "next_js" },
  { display: "Framework 7", value: "framework_7" },
  { display: "Rachet", value: "rachet" },
  { display: "PyTorch", value: "pytorch" },
  { display: "Neural Network Libraries", value: "neural_network_libraries" },
  { display: "Apache MXNet", value: "apache_mxnet" },
  { display: "ML.NET", value: "ml_net" },
  { display: "Infer.NET", value: "infer_net" },
  { display: "Accord.NET", value: "accord_net" },
  { display: "Chainer", value: "chainer" },
  { display: "Horovod", value: "horovod" },
  { display: "H2O Q", value: "h2o_q" },
  { display: "Robot Framework", value: "robot_framework" },
  { display: "Gauge", value: "gauge" },
  { display: "Pytest", value: "pytest" },
  { display: "Jest", value: "jest" },
  { display: "Mocha", value: "mocha" },
  { display: "Jasmine", value: "jasmine" },
  { display: "Nightwatch", value: "nightwatch" },
  { display: "Protractor", value: "protractor" },
  { display: "Cypress", value: "cypress" },
  { display: "TestProject", value: "testproject" },
  { display: "Galen Framework", value: "galen_framework" },
  { display: "WebDriverIO", value: "webdriverio" },
  { display: "OpenTest", value: "opentest" },
  { display: "Citrus", value: "citrus" },
  { display: "Karate", value: "karate" },
  { display: "Scrapy", value: "scrapy" },
  { display: "Truffle", value: "truffle" },
  { display: "Embark", value: "embark" },
  { display: "Etherlime", value: "etherlime" },
  { display: "OpenZeppelin Contracts", value: "open_zeppelin_contracts" },
  { display: "Brownie", value: "brownie" },
  { display: "Create Eth App", value: "create_eth_app" },
  { display: "Exonum", value: "exonum" },
  { display: "Hyperledger", value: "hyperledger" },
  { display: "Corda", value: "corda" },
  { display: "MultiChain", value: "multichain" },
  { display: "Meteor", value: "meteor" },
  { display: "Onsen UI", value: "onsen_ui" },
  { display: "SiteWhere", value: "sitewhere" },
  { display: "Electron", value: "electron" },
  { display: "Svelte", value: "svelte" },
  { display: "Aurelia", value: "aurelia" },
  { display: "Mithril", value: "mithril" },
  { display: "Bulma", value: "bulma" },
  { display: "Microdot", value: "microdot" },
  { display: "Rapidoid", value: "rapidoid" },
  { display: "Ktor", value: "ktor" },
  { display: "Scalatra", value: "scalatra" },
  { display: "Toolatra", value: "toolatra" },
];
