import NextAuthProvider from "@/provider/NextAuthProvider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AppBar from "@/components/custom/AppBar/AppBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-light-surface dark:bg-dark-surface `}
      >
        <NextAuthProvider>
          <div className="flex flex-col h-screen">
            <AppBar />
            <div className="flex-grow">{children}</div>
          </div>
        </NextAuthProvider>
      </body>
    </html>
  );
}
