// components/landing/FeaturesSection.tsx
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card";
import { Zap, Bot, Target, MessageCircleCode, LineChart } from "lucide-react"; // Example icons

const features = [
  {
    icon: Bot,
    title: "AI-Powered Questions",
    description: "Get realistic interview questions generated by advanced AI, tailored to various roles and topics like DSA, System Design, and more.",
  },
  {
    icon: Target,
    title: "Personalized Practice",
    description: "Optionally share your profile (experience, tech stack) to receive questions more relevant to your specific career goals.",
  },
  {
    icon: MessageCircleCode,
    title: "Instant AI Feedback",
    description: "Receive immediate, constructive analysis on your answers, highlighting strengths and areas for improvement.",
  },
  {
    icon: LineChart,
    title: "Track Your Progress",
    description: "Review past sessions, identify patterns in feedback, and see your skills improve over time. (Coming Soon!)",
  },
];

export default function FeaturesSection() {
  return (
    <section id="features" className="py-16 sm:py-24 bg-background">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-16">
          <h2 className="text-base font-semibold text-primary tracking-wide uppercase">Why Interview Hero?</h2>
          <p className="mt-2 text-3xl sm:text-4xl lg:text-5xl font-extrabold tracking-tight text-foreground">
            Everything You Need to Prepare
          </p>
        </div>
        <div className="grid md:grid-cols-2 gap-8 lg:gap-12">
          {features.map((feature) => (
            <div key={feature.title} className="flex gap-6">
              <div className="flex-shrink-0">
                <div className="flex items-center justify-center h-12 w-12 rounded-md bg-primary text-primary-foreground">
                  <feature.icon className="h-6 w-6" aria-hidden="true" />
                </div>
              </div>
              <div>
                <h3 className="text-xl font-semibold text-foreground">{feature.title}</h3>
                <p className="mt-1 text-muted-foreground">{feature.description}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}